## 📘 NumPy Comprehensive Notes for Data Analysis

In [6]:
import numpy as np

<h3 style="color:#0ea5e9; margin:6px 0;">🚀1. Introduction </h3>

- Numpy(Numerical Python): Core library for           numerical & scientific computing in Python
- Provides:
   - ndarray(N-dimensional array) -> fast & memory        efficient
   - Vectorized operations(nonneed of slow python        loops)


<h3 style="color:#22c55e; margin:6px 0;">🌱 1. Creating Arrays</h3>  

<h5 style="color:#d946ef; margin:6px 0;">1.1- From List or Tuples</h5> 

```python
a=np.array([1,2,3,4]) #1D arary
b=np.array([[1,2,3],[4,5,6]]) #Create a 2D array (matrix) from a list of lists


<h5 style="color:#d946ef; margin:6px 0;">1.2 - Predefined Array</h5> 

```python
np.zeros((4,4))  # 4*4 arrays of zeros
np.ones((2,4))   #2*4 arrays of ones
np.full((2,3),7) # 2*3 filled with 7
np.eye(4) # Identity Matrix

<h5 style="color:#d946ef; margin:6px 0;">1.3 - Ranges</h5> 

```python
np.arange(0,10,2) #[0,2,4,6,8]
np.linspace(0,1,5) # 5 equally spaced points b/w 0 & 1

<h5 style="color:#d946ef; margin:6px 0;">1.4 - Random arrays</h5>

In [7]:
np.random.rand(3,2) # Uniform distribution[0,1]

array([[0.16217551, 0.45890753],
       [0.37625881, 0.40166945],
       [0.57447057, 0.67461645]])

In [8]:
np.random.randn(3,2) #standard normal distribution

array([[-0.43193507,  0.85690317],
       [-0.11534306, -0.12570315],
       [-0.63225112, -0.5875727 ]])

In [9]:
np.random.randint(1,10,5) #random 5 integers b/w 1 &10

array([3, 8, 3, 1, 3], dtype=int32)

In [79]:
# Random numbers
random_array = np.random.random((3, 3))  # random values in a given shape
print("Random array:\n", random_array)

Random array:
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]


<h3 style="color:#22c55e; margin:6px 0;">🔍2.Array attributes</h3>  

In [10]:
arr=np.array([[1,2,3],[4,5,6]])

```python
arr.shape      #dimensions (rows,cols)
arr.ndim       #no of dimensions
arr.size       #total elements
arr.dtype     #data type
arr.itemsize #bytes per element 

In [11]:
arr.ndim

2

In [12]:
arr.itemsize

8

<h3 style="color:#22c55e; margin:6px 0;">✂️ 3. Indexing, Slicing, Subsetting</h3>

- 2nd index we pass is +1 index
- eg . arr[0:2 , 1:3] we've to traverse till 1 hence 1+1=2 , for 3 we've to traverse till 2 thus,2+1=3

In [13]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr[0,1] #row 0 , col 1

np.int64(2)

In [15]:
arr[:,1] # all rows,col1

array([2, 5, 8])

In [16]:
arr[1,:] # 1st row , all column

array([4, 5, 6])

In [17]:
arr[0:2 , 1:3] #subarray 0:2 row 0 to 1 , from col 1 to 2

array([[2, 3],
       [5, 6]])

<h5 style="color:#d946ef; margin:6px 0;"> 🧩Boolean Indexing</h5>

In [18]:
arr[arr>5] #elements greater than 5 🧩

array([6, 7, 8, 9])

In [78]:
# Boolean indexing
bool_index = arr > 3
print("Boolean indexing (arr > 3):", bool_index)
filtered_array = arr[bool_index]
print("Filtered array:", filtered_array)

Boolean indexing (arr > 3): [[False False False]
 [ True  True  True]
 [ True  True  True]]
Filtered array: [7 8 9 4 5 6]


<h5 style="color:#d946ef; margin:6px 0;"> 🧩Fancy Indexing</h5>

In [19]:
arr[[0,2],[1,2]] #elements at (0,1) & (2,2)

array([2, 9])

<h5 style="color:#d946ef; margin:6px 0;"> 🧩Where</h5>

In [70]:
arr

array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])

In [68]:
condi_array=np.where(arr>5,arr*3,arr)
display(condi_array)

array([[ 1,  2,  3],
       [21, 24, 27],
       [ 4,  5, 18]])

In [69]:
condi_array=np.where(arr>5,"true","false")
display(condi_array)

array([['false', 'false', 'false'],
       ['true', 'true', 'true'],
       ['false', 'false', 'true']], dtype='<U5')

<h3 style="color:#22c55e; margin:6px 0;">➕ 4. Array Operations</h3>

In [20]:
a1=np.array([1,2,3,4,5])
a2=np.array([8,9,9,4,5])
display(a1)
display(a2)

array([1, 2, 3, 4, 5])

array([8, 9, 9, 4, 5])

<h5 style="color:#d946ef; margin:6px 0;"> 🧩Element-Wise/h5>

In [74]:
display(a1+a2)
display(a1-a2)
display(a1*a2)
display(a1/a2)
display(a1**a2)

array([ 9, 11, 12,  8, 10])

array([-7, -7, -6,  0,  0])

array([ 8, 18, 27, 16, 25])

array([0.125     , 0.22222222, 0.33333333, 1.        , 1.        ])

array([    1,   512, 19683,   256,  3125])

In [75]:
arr2=np.concatenate((a1,a2))
arr2

array([1, 2, 3, 4, 5, 8, 9, 9, 4, 5])

<h5 style="color:#d946ef; margin:6px 0;"> 🧩Aggregate functions</h5>

In [22]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
display(arr.sum())
display(arr.mean())
display(arr.min())
display(arr.max())
display(arr.std())
display(arr.var())

np.int64(45)

np.float64(5.0)

np.int64(1)

np.int64(9)

np.float64(2.581988897471611)

np.float64(6.666666666666667)

<h5 style="color:#d946ef; margin:6px 0;"> 🧩Axis-Based-Operations</h5>

In [45]:
#methos1:
display(np.sum(arr, axis=0))  # column-wise
display(np.sum(arr, axis=1))  # row-wise

array([12, 15, 18])

array([ 6, 24, 15])

In [46]:
#methos2:
display(arr.sum(axis=0))
display(arr.sum(axis=1))

array([12, 15, 18])

array([ 6, 24, 15])

In [77]:
# Sum of all elements in an array
sum_all = np.sum(a)
print("Sum of all elements:", sum_all)

Sum of all elements: 6


<h3 style="color:#22c55e; margin:6px 0;">🔄 5. Reshaping & Manipulation</h3>

In [47]:
arr.reshape(3,3)

array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])

In [48]:
arr.flatten() #1-D

array([1, 2, 3, 7, 8, 9, 4, 5, 6])

In [49]:
arr.T #transpose

array([[1, 7, 4],
       [2, 8, 5],
       [3, 9, 6]])

In [76]:
# Reshape an array
reshaped = np.arange(12).reshape(3, 4)
print("Reshaped array:\n", reshaped)

Reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


<h5 style="color:#d946ef; margin:6px 0;"> 🧩5.1 -Stacking:</h5>

In [50]:
display(a1)
display(a2)

array([1, 2, 3, 4, 5])

array([8, 9, 9, 4, 5])

In [51]:
np.vstack([a1,a2])

array([[1, 2, 3, 4, 5],
       [8, 9, 9, 4, 5]])

In [52]:
np.hstack([a1,a2])

array([1, 2, 3, 4, 5, 8, 9, 9, 4, 5])

In [53]:
np.column_stack([a1,a2])

array([[1, 8],
       [2, 9],
       [3, 9],
       [4, 4],
       [5, 5]])

<h5 style="color:#d946ef; margin:6px 0;"> 🧩5.2 -Splitting:</h5>

In [33]:
c=np.arange(0,32,2).reshape(4,4)
c

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [34]:
np.split(c,2) #split into 2 parts

[array([[ 0,  2,  4,  6],
        [ 8, 10, 12, 14]]),
 array([[16, 18, 20, 22],
        [24, 26, 28, 30]])]

In [35]:
np.hsplit(c,4)

[array([[ 0],
        [ 8],
        [16],
        [24]]),
 array([[ 2],
        [10],
        [18],
        [26]]),
 array([[ 4],
        [12],
        [20],
        [28]]),
 array([[ 6],
        [14],
        [22],
        [30]])]

In [36]:
np.vsplit(c,4)

[array([[0, 2, 4, 6]]),
 array([[ 8, 10, 12, 14]]),
 array([[16, 18, 20, 22]]),
 array([[24, 26, 28, 30]])]

<h3 style="color:#22c55e; margin:6px 0;">🔄 6. Broadcasting </h3>

- Rules for performing operations on arrays with different shapes.
- Tip: Use broadcasting to avoid memory-heavy       loops
- Automatic shape expansion for compatible arrays
- Works when shapes are compatible (e.g., (3,1) with (1,4))



In [37]:
a=np.array([1,2,3])
b=np.array([[10],[20],[30]])
display(a)
display(b)
display(a+b)

array([1, 2, 3])

array([[10],
       [20],
       [30]])

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

<h3 style="color:#22c55e; margin:6px 0;">🔄 7. Linear Algebra </h3>

In [38]:
display(np.dot(a,b)) #matrix multiplication
display(a@b)#matrix multiplication
display(np.matmul(a,b))   #matrix multiplication
display(np.linalg.inv(c))  #inverse
display(np.linalg.det(c)) # determinant
display(np.linalg.eig(c)) # eigenvalues & vectors

array([140])

array([140])

array([140])

array([[ 4.50359963e+14, -2.25179981e+14, -9.00719925e+14,
         6.75539944e+14],
       [-1.20095990e+15,  1.35107989e+15,  9.00719925e+14,
        -1.05083991e+15],
       [ 1.05083991e+15, -2.02661983e+15,  9.00719925e+14,
         7.50599938e+13],
       [-3.00239975e+14,  9.00719925e+14, -9.00719925e+14,
         3.00239975e+14]])

np.float64(-4.7331654313260826e-29)

EigResult(eigenvalues=array([ 6.49284984e+01, -4.92849839e+00, -3.04550265e-15,  9.05867932e-17]), eigenvectors=array([[-0.11417645, -0.7327781 , -0.48846795, -0.01936986],
       [-0.3300046 , -0.28974835,  0.83598112, -0.38216644],
       [-0.54583275,  0.15328139, -0.20655839,  0.82244247],
       [-0.76166089,  0.59631113, -0.14095478, -0.42090617]]))

<h3 style="color:#22c55e; margin:6px 0;">🔄 8. Useful Functions </h3>

In [39]:
display(np.unique(arr))
display(np.sort(arr))
display(np.argsort(arr))
display(np.argmax(arr))
display(np.argmin(arr))
display(np.where(arr>5,1,0))
display(np.isin(arr,[2,3]))


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

np.int64(8)

np.int64(0)

array([[0, 0, 0],
       [0, 0, 1],
       [1, 1, 1]])

array([[False,  True,  True],
       [False, False, False],
       [False, False, False]])

<h3 style="color:#22c55e; margin:6px 0;"> 🧼 10. Handling Missing Data (NaN)</h3>

In [58]:
arr1 = np.array([1, 2, np.nan, 4])
display(np.isnan(arr1)) #check NaN 
np.nan_to_num(arr1)  # replace NaN with 0
display(np.nanmean(arr1)) # mean ignoring NaN
display(np.isinf(arr))
display(np.clip(arr, 0, 10)  )

array([False, False,  True, False])

np.float64(2.3333333333333335)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])

<h3 style="color:#22c55e; margin:6px 0;">🎲 11. Random Module Utilities </h3>

In [41]:
display(np.random.rand(3,2))
display(np.random.randint(1,10,5))
display(np.random.randint(0, 10, size=(3, 3)))
display(np.random.shuffle(arr))
display (np.random.permutation (arr))
        

array([[0.20335034, 0.98222304],
       [0.21768059, 0.77669518],
       [0.57962265, 0.6818707 ]])

array([8, 6, 1, 6, 3], dtype=int32)

array([[8, 3, 2],
       [5, 9, 1],
       [1, 9, 7]], dtype=int32)

None

array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])

In [42]:
np.random.seed(42)
#→ make results repeatable
#Always fix random seed (np.random.seed) for reproducibility..

In [81]:
# Seed for reproducibility
np.random.seed(42)
random_seeded = np.random.random((2, 2))
print("Random array with seed:\n", random_seeded)

Random array with seed:
 [[0.37454012 0.95071431]
 [0.73199394 0.59865848]]


In [80]:
# Random numbers
random_array = np.random.random((3, 3))  # random values in a given shape
print("Random array:\n", random_array)

Random array:
 [[0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643]]


<h3 style="color:#22c55e; margin:6px 0;">🎲 12. Conversions </h3>

In [43]:
display(arr.tolist())      # to Python list
display(arr.astype(int))  # change type

[[1, 2, 3], [7, 8, 9], [4, 5, 6]]

array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])

<h3 style="color:#22c55e; margin:6px 0;">🧠 13. NumPy + Pandas Synergy</h3>

In [44]:
import pandas as pd
df = pd.DataFrame(arr)
df

0  1  2
0  1  2  3
1  7  8  9
2  4  5  6

<h3 style="color:#22c55e; margin:6px 0;">🧠 14. File I/O</h3>

```python
- Save: np.save('file.npy', arr)
- Load: np.load('file.npy')
- CSV: np.genfromtxt('data.csv', delimiter=',')






<h3 style="color:#22c55e; margin:6px 0;">🧠15. Histogram I/O</h3>

In [55]:
hist, bins = np.histogram(arr, bins=10)
hist

array([1, 1, 1, 1, 0, 1, 1, 1, 1, 1])

<h3 style="color:#60a5fa; margin:6px 0;">📘Vectors</h3>

In [59]:
vector=np.array([1,2,3])
vector

array([1, 2, 3])

<h3 style="color:#60a5fa; margin:6px 0;">📘Matrix</h3>

In [60]:
matrix=np.array([[1,2,3],[4,5,6]])
matrix

array([[1, 2, 3],
       [4, 5, 6]])

<h3 style="color:#60a5fa; margin:6px 0;">📘Tensor</h3>

In [63]:
tensor=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
tensor #-> multi-dimensional array

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

<h3 style="color:#22c55e; margin:6px 0;">🧠16.Filtering with mask </h3>

In [66]:
mask=arr>5
arr[mask]

array([7, 8, 9, 6])

In [67]:
x=arr<5
arr[x]

array([1, 2, 3, 4])

# 🧠 NumPy Memory Map for Data Analysis

## 📌 1. Array Creation
- `np.array()`, `np.zeros()`, `np.ones()`, `np.eye()`
- `np.arange()`, `np.linspace()`

## 📐 2. Array Properties
- `.shape`, `.ndim`, `.size`, `.dtype`, `.itemsize`

## ✂️ 3. Indexing & Slicing
- `arr[0, 1]`, `arr[:, 1]`, `arr[1:, :]`
- Boolean indexing: `arr[arr > 2]`

## 🔄 4. Reshaping & Manipulation
- `reshape()`, `flatten()`, `transpose()`
- `concatenate()`, `split()`

## ➕ 5. Math Operations
- Element-wise: `+`, `-`, `*`, `/`, `**`
- Aggregations: `sum()`, `mean()`, `std()`, `min()`, `max()`
- Axis-based: `np.sum(arr, axis=0)`

## 📊 6. Statistics
- `median()`, `percentile()`, `corrcoef()`, `histogram()`

## 🎲 7. Random Module
- `rand()`, `randint()`, `seed()`

## 📁 8. File I/O
- `np.save()`, `np.load()`
- `np.genfromtxt()` for CSVs

## 🧮 9. Linear Algebra
- `inv()`, `det()`, `eig()`, `solve()`, `norm()`

## 🧩 10. Broadcasting
- Automatic shape expansion for compatible arrays

## ⚡ 11. Performance Tips
- `vectorize()`, `memmap()`, `set_printoptions()`
- `%timeit` for benchmarking

## 🧠 12. Logical & Set Ops
- `any()`, `all()`, `logical_and()`, `unique()`, `intersect1d()`

## 🧼 13. Handling Missing Data
- `isnan()`, `isinf()`, replacement logic

## 📦 14. Structured Arrays
- Custom `dtype` for mixed-type tabular data

## 🔗 15. NumPy + Pandas
- Convert arrays to DataFrames: `pd.DataFrame(arr)`
- Use NumPy inside `apply()` for speed

---

## 🌟 Pro Tips
- `np.where()` for conditional logic
- `np.clip()` to clean outliers
- `np.argsort()` for ranking
- `np.cumsum()`, `np.diff()` for time series
- `np.tile()`, `np.repeat()` for reshaping
- `np.allclose()` for float comparison
- `np.lib.stride_tricks.sliding_window_view()` for advanced windowing

---

## 🚀 Showcase Ideas
- ✅ Mini-project: Pure NumPy EDA on Iris Dataset  
- 📸 Carousel: “10 NumPy Tricks That Made My Code 10x Faster”  
- 📘 README: “Why I Chose NumPy First for Data Analysis”


In [ ]:
structured array